### ISSUE TITLE
[BUG] Some non-default language CE not visible in TransFusion Connector

### ISSUE THREAD

**Issue by ErHaWeb** [CodersCare/transfusion#12]
In some cases, which are not yet completely clear to me, content elements of the non-default language are missing in the TransFusion Connector.

For demonstration purposes, I have attached a test database and a test site configuration (they are the same ones that you use for your tests and that you sent me for demonstration on t3cmd24.).

Example Site Configuration: [config.yaml.zip](https://github.com/CodersCare/transfusion/files/14742665/config.yaml.zip)
Example DB: [typo3_dump.tar.gz](https://github.com/CodersCare/transfusion/files/14742669/typo3_dump.tar.gz)

In this case I notice that in the language "Nederlands" [6] the contents with the uids 513 and 524, which are visible as unconnected contents in the Page module, are missing in the TransFusion Connector. Unfortunately, I cannot yet provide any further information on the possible cause.

**Comment by Bunnyfield** [comment]
This seems to be a regression that happened with the latest change 2de95de9b9c96534dc4d8cfb3035dbf3f001021e, since with commits before it was still working.

**Comment by Bunnyfield** [comment]
Fixed and forced pushed it

**Comment by ErHaWeb** [comment]
Unfortunately, this bug has not yet been completely fixed. In the latest version, I still encounter situations where content elements that are visible in the page module in the non-default language do not appear in the TransFusion Connector. The problem only seems to occur if the elements were originally created based on a different non-default language.

![Bildschirmfoto 2024-03-26 um 13 45 20](https://github.com/CodersCare/transfusion/assets/5416710/340aad2d-888e-4f4c-b23a-40c412081635)

![Bildschirmfoto 2024-03-26 um 13 45 45](https://github.com/CodersCare/transfusion/assets/5416710/ef82d67c-1c3d-4d59-a355-a2bcef6c5040)

**Comment by Bunnyfield** [comment]
Looking on the screenshot the actual cause of the problem seems to be that there are no elements in the default language at all. Current testing scenarios always contained at least some elements there, so we will add the "default language empty" scenario and try to reproduce the error.

Still this would be another bug than this one - so I will come up with a new ticket as soon as the behaviour has been reproduced.
